# Trigger Test-1
name: Enterprise DevSecOps CICD Pipeline
on:
  push:
    branches:
      - qa
    paths:
      - client/**
      - server/**
      - .github/workflows/qa-cicd.yml
      - .github/workflows/Snyk.yml
permissions:
  contents: write
  id-token: write
  
jobs:
  Snyk-scan:
    name: Snyk Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
         node-version: '20'
         
      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

       - name: Run Snyk Code Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk code test \
            --severity-threshold=medium
